### ISSUE TITLE
Customization of map serialization in scalapb-json4s

### ISSUE THREAD

**Issue by gontard** [scalapb/ScalaPB#1030]
We use [`scalapb-json4s`](https://github.com/scalapb/scalapb-json4s) to read/write instances of the generated scalapb classes into ElasticSearch. Because of the ES field count limit (1000 by default), we had to customize the way `map` are written. Instead of a JSON object having map keys as propertied, we serialize an array of object (`[{key, value}*]`), otherwise ES creates one field for each different map key.

For example, we went from:
```json
{"map":{"k1":"v1","k2":"v1","k3":"v1","k4":"v1"}}
```

to:
```json
{"map":[
   {"key":"k1","value":"v1"},
   {"key":"k2","value":"v2"},
   {"key":"k3","value":"v3"},
   {"key":"k4","value":"v4"}
]}
```
---

To do that we had to inline an important part of `scalapb-json4s` since most of the stuff is private. 

I wonder if this alternative export could be part of `scalapb-json4s` (activated by a setting) or if it would be possible to ease the extension/customization of the existing parser|writer.
Happy to open a PR if you need help.

**Comment by thesamet** [comment]
The representation you want to see is the one you'd get if `isMapField` returned `false` in [here](https://github.com/scalapb/scalapb-json4s/blob/1a7fe0fe2087892d7ec556e7f293ed287115b8bd/src/main/scala/scalapb/json4s/JsonFormat.scala#L289) since the underlying representation of maps is actually messages with `key` and `value` fields. I am fine with a PR that introduce a setting named like `mapEntriesAsKeyValuePairs` that would be negated and `&&`'ed in that `if (fd.isMapField)` above. This needs to be applied both for parsing and formatting.
