### ISSUE TITLE
Feature: add custom types to the generator

### ISSUE THREAD

**Issue by borissmidt** [scalapb/ScalaPB#1125]
It would be nice if we could register some an type conversion between the grpc types and internal types.
Like an configuration object like `my.conversions.conversions.InstantToJoda` which would convert an protobuf.instant directly to a joda.instant avoiding you to have to write a manual copy and class definition of the proto types.

I.e. a bit like most json libaries allow for with implicits that you have a custom conversion between String and Time for example.
Or `Object(unit: String, value: Double)` for an measured value like Power, Frequency etc.

**Comment by thesamet** [comment]
Hi @borissmidt , the feature you are requesting is already available.

**Comment by borissmidt** [comment]
Oh cool, i had read the documentation and didn't find it yet. I'm looking forward to the updated documentation and to try it out.

**Comment by thesamet** [comment]
In the mean time, the crux of it is as follows, add a proto with [package-scoped options](https://scalapb.github.io/docs/customizations#package-scoped-options)

```
syntax = "proto2";

package myexample;

import "scalapb/scalapb.proto";

option (scalapb.options) = {
  scope: PACKAGE
  field_transformations : [
    {
      when : {
        type: TYPE_MESSAGE
        type_name: ".google.protobuf.Timestamp"
      }
      set : {[scalapb.field] {type : 'some.external.MyInstant' }}
    }
  ]
};
```

Now you need to make sure there's an implicit `TypeMapper` to convert between `MyInstant` and `com.google.protobuf.timestamp.Timestamp`. If `MyInstant` is a class you own, the typemapper can be added to its companion object. If it's a third party (like Joda), then the typemapper can be added to a parent package of the generated code (see the end of this [section](https://scalapb.github.io/docs/customizations#custom-types)).

Note the dot prefix in the `type_name` field above, it is needed as [described here](https://github.com/protocolbuffers/protobuf/blob/68cb69ea68822d96eee6d6104463edf85e70d689/src/google/protobuf/descriptor.proto#L187-L192). In this example we assume the user's package is not named `google` or `google.protobuf` since then the type_name could be relative.

**Comment by borissmidt** [comment]
We have some problem with these `scalapb.options` in the proto files that other languages, python, don't find the scalapb.proto file and then fail when generating code.

Also what would happen if multiple files have the same package and define a scalapb.option. 
we had a lot of issue when we could only define `flatpackage=true` once causing us to rewrite most of our `.proto` files.

It would be cool however if it was possible to have a seperate 'meta' scalapb.proto file to set the settings for the full generator.

**Comment by thesamet** [comment]
For python compatibility, you could either generate python code for scalapb.proto using protoc, or if you only reference scalapb.proto from a single options file, you could exclude the options file when generating python code.

Only one file per *proto* package can define package-scoped options.

> It would be cool however if it was possible to have a seperate 'meta' scalapb.proto file to set the settings for the full generator.

You can already define a scalapb.proto for your top-level package name, and all subpackages automatically inherit it, and could also override any setting. You can't define it globally (at the root package level), since that would interfere with third-party protos like Google (for example, they are pre-compiled with flat_package=false).

Please let me know if there's any part of the original issue that is not addressed by the above. If there are other issues (not specific to custom types), feel free to open additional github issue(s).

**Comment by borissmidt** [comment]
Oke clear i'll take this knowledge to the rest of the team.
Thank you for being so helpful and taking the time for answering my questions!

**Comment by borissmidt** [comment]
It works thank you for the help i think it would be a good idea to add a not in the documentation that version `0.10.1` needs to be used.

**Comment by borissmidt** [comment]
Btw can i also define replacement types for any user of my 'common proto types' 
i.e. for example if i define an Interval so i can reuse it in other projects:

```
package my.common.types
message Interval {
    google.protobuf.Timestamp start = 1;
    google.protobuf.Timestamp end = 2;
}
```
Can i add this to the package so any consumer of my protofiles would get `custom.Interval` in there project?
Or do they each time have to define this transformer themselfs on there package level with the implicit in there package? 
```
syntax = "proto3";

package my.common.types;

import "scalapb/scalapb.proto";

option (scalapb.options) = {
  scope: PACKAGE
  field_transformations : [
    {
      when : {
        type: TYPE_MESSAGE
        type_name: ".my.common.types.Interval"
      }
      match_type: EXACT
      set : {[scalapb.field] {type : 'custom.Interval' }}
    }
  ]
};
```

**Comment by thesamet** [comment]
@borissmidt , for your own types, you can use standard scalapb type customizations ([documented here](http://localhost:3000/docs/customizations#message-level-custom-type-and-boxing)) and they automatically applied for users of your protos.

**Comment by borissmidt** [comment]
Oh wonderful those are a lot of options, thank you for the help.
