### ISSUE TITLE
Feature request: add an option to control field scope

### ISSUE THREAD

**Issue by aaabramov** [scalapb/ScalaPB#1180]
I would like to generate a message like

```scala
case class Person(name: String, protected val age: Int)
```

I have found a workaround how to do it:
```protobuf
message StreamUpdated {
  string name = 1;
  int32 age = 2 [
    (scalapb.field).annotations = 'protected val'
  ];
}
```
But that is not obvious for users, IMHO. 
Either we can document this behaviour or add a separate option, e.g. `field_scope`.

**Comment by thesamet** [comment]
Hi @aaabramov , feel free to send a PR that documents it, either in https://scalapb.github.io/docs/customizations#adding-annotations and/or adding an FAQ right after this [one](https://scalapb.github.io/docs/faq#how-do-i-mark-a-generated-case-class-private). I want to refrain from adding specific options for scope: since there are multiple of them (protected, private, `private[pkg]`, `private[this]`), then there might be other modifiers that need to be modeled by ScalaPB. The other reason is that I prefer that the possibility of marking scope is an "unsupported feature". This way ScalaPB and other code generators can assume all fields are public without having to worry about one more detail, and users can expect that if they play with scope things may break in the future.
