### ISSUE TITLE
Option to relax string utf8 parsing requirement 

### ISSUE THREAD

**Issue by mitchellehlers** [scalapb/ScalaPB#1293]
I am looking for a option to enable support for parsing proto which contains Strings that contain non-UTF8. 

[Version 0.10.0](https://github.com/scalapb/ScalaPB/blob/master/CHANGELOG.md#0100) introduced Strings being parsed using CodedInputStream.readStringRequireUtf8 instead of CodedInputStream.readString. [readString()](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/CodedInputStream.java#L285-L289) would replace the offending bytes with the standard UTF-8 replacement character, '?'. The new function throws a exception and the proto fails to parse.

Having this option would help in supporting legacy devices with a UTF8 issue, and keep on the current versions of ScalaPB.
We can't update the devices, but still have to support them. We are trying to avoid being tied to a specific version. We are currently using version 0.9.8 until we find a solution.    

Thanks for considering this request.

**Comment by bjhartin** [comment]
I agree we need some way to handle this - we don't have control over these devices that send the messages.

**Comment by thesamet** [comment]
Hey there, the current behavior is consistent with the [protobuf language guide](https://developers.google.com/protocol-buffers/docs/proto3#scalar) and the Java implementation also uses `readString`

>  A string must always contain UTF-8 encoded or 7-bit ASCII text, and cannot be longer than 232.

If you are expecting malformed strings, switch to using `bytes` as the data type in the proto used by the Scala application. This change is not going to require any change to the legacy devices as `bytes` and `string` are compatible in the binary representation. On the Scala side, you will get an `ByteString`. You can use ScalaPB [custom types](https://scalapb.github.io/docs/customizations#custom-types) to convert it to `String` using any algorithm you want (I believe `toStringUtf8` will do the replacement `?`). You can also apply the custom type conversion to all bytes fields at once using [field transformations](https://scalapb.github.io/docs/transformations). Hope this helps!

**Comment by bjhartin** [comment]
@thesamet I need to use field transformations, I think, because we don't control the original proto files.  However, I can't blindly convert `bytes` to another type because some fields must remain as bytes.  I see in the docs that I can specify the field name in a field descriptor in the `when` clause, but can I specify a package and class name as I would for auxiliary file or field options?  Or, can I define transformations as auxiliary options?

**Comment by thesamet** [comment]
The field transformations only apply within the package they are defined in when it's in package-scoped options. There's currently no way to restrict a field transformation by the name of the message it's in.

**Comment by thesamet** [comment]
With auxiliary options, you can have fine grained control over exactly which fields to transform.

**Comment by bjhartin** [comment]
Here's what we did (if there's a better way please let me know):

- We pull the .proto files locally in our CI build
- We pre-process them, doing two things:
  - Replace existing string fields with bytes
    - This step is unavoidable.  We don't own the protos.
  - Specify the scala type as "String" (our TypeMapper handles non-UTF8 chars)
    - There was no need for a custom type, we just needed to intercept non-UTF8 strings and remove/replace the bad bytes

I don't think I can do the second part with ScalaPB in a 'global' way.  We tried:

- Using field transformations which didn't work because I don't think I can write a when clause like "all bytes fields except A.b, C,d. E.f, ...".  This is what I need because we have relatively few 'bytes' fields and lots of 'string' fields.
- Hand-writing auxiliary options has the same problem as field transformations: the target is really "all bytes fields except ..."

An alternative to our approach might have been to generate field auxiliary options instead of adding the field type in the proto file.  The addition of the fields had to account for fields that already had options, e.g. '[x = y, p = q]' so it's a bit fragile in my opinion.

**Comment by thesamet** [comment]
Hey @bjhartin ,  one thing you could try is to replace the second part of the pre-process with the following:

Add a field transformation to change all `bytes` fields to a String, then add aux_field_options to revert back the type to `com.google.protobuf.ByteString` the byte fields you want to retain as bytes. This will require you to have two typemappers, the one you already have, and a trivial one: `ByteString` to `ByteString`.

**Comment by mitchellehlers** [comment]
This conversation was helpful. Thank you @thesamet and @bjhartin.
