### ISSUE TITLE
When passing an empty Array[Byte] into parseFrom(), it will return the default instance

### ISSUE THREAD

**Issue by YunLiaw** [scalapb/ScalaPB#194]
Hi, 

I just found that passing a arbitrary byte array into the parseFrom function, it will throw the InvalidProtocolBufferException. 

But if I pass an empty byte array into the parseFrom function, it will return the default instance. Is it an intended behavior? 

I use protobuf 2.6 and scalaPB 0.5.42

Thanks,
Yun

**Comment by thesamet** [comment]
Very roughly speaking, the wire format is a list of (field number, [wire type](https://developers.google.com/protocol-buffers/docs/encoding#structure), value) triples. If all the fields in a message are optional, then an empty byte array represents the default instance.

The encoding is such that a random byte array is most likely to not form a valid message, so that's expected as well.

**Comment by YunLiaw** [comment]
Ok. But the messages with required type will also return the default instance. It looks a little bit tricky.

**Comment by thesamet** [comment]
That could be an issue. I'll reopen.
