### ISSUE TITLE
CrossProject not working

### ISSUE THREAD

**Issue by RookieMaus** [scalapb/ScalaPB#234]
Not sure if this is an SBT issue or one of ScalaPB. But most probably it's a Layer 8 problem:

I want to use a protoproject as crossProject between jvm and scala.js, but sadly nothing gets compiled:

```
  lazy val proto = (crossProject.crossType(CrossType.Pure) in file("proto"))
    .settings(generalSettings: _*).
    jvmSettings(
      libraryDependencies += "com.trueaccord.scalapb" %% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion % "protobuf",
      PB.targets in Compile := Seq(
        scalapb.gen() -> (sourceManaged in Compile).value
      )
    ).
    jsSettings(
      libraryDependencies ++= Seq(
        "com.trueaccord.scalapb" %%% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion,
        "com.trueaccord.scalapb" %%% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion % "protobuf"
      ),
      PB.targets in Compile := Seq(
        scalapb.gen() -> (sourceManaged in Compile).value
      )
    )

  lazy val protoJs = proto.js
  lazy val protoJVM = proto.jvm

  lazy val server = (project in file("server"))
  .enablePlugins(PlayScala)
  .settings(generalSettings: _*)
  .settings(
    name := "server",
    libraryDependencies ++= Seq(
      CrossDependencies.scalaTest,
      CrossDependencies.scalactic,
      CrossDependencies.scalaTags,
      "com.typesafe.play" %% "play-json" % "2.6.0-M1"),
    scalaJSProjects := Seq(client),
    pipelineStages in Assets := Seq(scalaJSPipeline),
    compile in Compile := ((compile in Compile) dependsOn scalaJSPipeline).value
  )
  .dependsOn(protoJVM)

  lazy val client = (project in file("client"))
  .enablePlugins(ScalaJSPlugin, ScalaJSWeb)
  .settings(oneSetToRuleThemAll: _*)
  .settings(
    name := "client",
    libraryDependencies += CrossDependencies.scalaTags,
    persistLauncher := true
    //  persistLauncher in Test := false,
    //  mainClass in Compile := Some("org.athonae.PlayHolder")
  )
  .dependsOn(protoJs)
```

*.proto sources are in `proto/src/main/protobuf`

Any ideas what could be the cause here? Another shared project works just fine. (Other project, not proto related, but basically same setup)

**Comment by thesamet** [comment]
If you type in SBT `protoJS/protocSources` you'll see something like:
```[info] * /dir/.../proto/.js/src/main/protobuf```

Similarly for `protoJVM/protocSources`. It turns out that sbt-protoc is looking for files at the wrong place. To fix that, please specify PB.protoSources explicitly. The proto project in build.sbt should look like this:

```
lazy val proto = (crossProject.crossType(CrossType.Pure) in file("proto"))
  .settings(
    PB.targets in Compile := Seq(
      scalapb.gen() -> (sourceManaged in Compile).value
    ),
    // The trick is in this line:
    PB.protoSources in Compile := Seq(file("proto/src/main/protobuf")),
    libraryDependencies ++= Seq(
      "com.trueaccord.scalapb" %%% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion,
      "com.trueaccord.scalapb" %%% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion % "protobuf"
    )
  )
```

I added an example project here: https://github.com/thesamet/sbt-protoc/tree/master/examples/scalajs-multiproject

**Comment by kadriaen** [comment]
Is it me or does this trick not work any more with the latest version of the cross project plugin?
It always gives me a "Protobufs files found, but PB.targets is empty."  error.
https://github.com/portable-scala/sbt-crossproject

**Comment by kadriaen** [comment]
I tested the example you provided and it works fine, my bad; the problem was related to my project setup.

My issue was that I could not use an absolute path when setting the protoSources param in project templates that can be used on nested projects (... needed to have something generic).
So instead of:
    `PB.protoSources in Compile := Seq(file("proto/src/main/protobuf"))`
I now define it like this:
    `Compile / PB.protoSources := Seq(baseDirectory.value / ".." / "src" / "main" / "protobuf")`

On the crossProject the baseDirectory is the directory of the crossProject managed  (.jvm / .js / ...) projects.
I tried it on the example you provided, and it seems to work fine there as well.
