### ISSUE TITLE
No last released documentation in https://scalapb.github.io

### ISSUE THREAD

**Issue by angelcervera** [scalapb/ScalaPB#279]
In https://scalapb.github.ioyou have the documentation related to the current development process and not the last released version.

For example, now is information about "0.6.0-pre4" but if you go to github, the README says: 
Version	Description
0.4.x	Stable, works with Protobuf 2.6.x
0.5.x	Now stable: supports Protobuf 2.6.x and Protobuf 3.1.x.
0.6.x	To be released.

So the information in the site is at least confusing to people. I think that it is wrong.

By the way: How to access to the 0.5.x site version?

**Comment by thesamet** [comment]
The documentation at scalapb.github.io applies to all versions at once. If there are any differences (new features) the version they are introduced is explicitly mentioned. The docs should work for you no matter if you are on 0.5.x or 0.6.x. If you find any inaccuracy or a confusing part in the documentation please let me know.

**Comment by angelcervera** [comment]
One example of mixing versions:
In FAQ, reference to
`scalaSource in PB.protobufConfig := sourceManaged.value`
What is that? Are you talking about version 0.5 or 0.6 or what? I trying to migrate from version "0.5.43" to the last "0.5.x" versions.

Do you think that it is a good practice to maintain the same documentation for all versions and don't tied that to the version? Because, basically, you say that the documentation of the version that I am using in production (0.5.43) is lost. right? Because if I need to migrate is because is not compatible.
Maybe is a good idea explain that in the documentation, because it is the last thing that people expect.

**Comment by thesamet** [comment]
The example you refer to in the FAQ applies to all versions of ScalaPB equally (it's about the SBT plugin, not ScalaPB itself)

Are you facing a specific issue when migrating from 0.5.43 to the latest 0.5.x? This should be a straightforward upgrade. If it's not a straightforward upgrade, I'd add a FAQ or something similar.

I think having a single site doc for all versions is fine because of the way ScalaPB is being developed. We have very frequent releases which are backwards compatible and in general features are getting added and bugs fixed, but as far as I can remember, we have never broken our own public APIs. If we were to make a drastic change that would impact how you use ScalaPB, I'd agree that a separate copy of the documentation would be a good choice.

If you want to dig how the docs look at a certain point in time, you can explore this git repository: https://github.com/scalapb/scalapb.github.io

Hope this helps, and let me know if you encounter any concrete issue as you are migrating and using ScalaPB. Will be happy to help.

**Comment by angelcervera** [comment]
Ok, so that is my misunderstand.
I am talking about sbt pluging and scalapb as a one thing.

My problem is with sbt-scalapb (now sbt-protoc). Following the scalapb migration document, I must to migrate to other different sbt plugin so it is necessary to change the sbt settings.

I am going to post my question in https://groups.google.com/forum/#!forum/scalapb

Thanks a lot for yout time.
Regards.
