### ISSUE TITLE
ScalaPBC support for scalapb.UdtGenerator

### ISSUE THREAD

**Issue by worldsense-tms** [scalapb/ScalaPB#338]
As discussed in https://github.com/scalapb/ScalaPB/issues/210#issuecomment-329272744, it would be nice for ScalaPBC to have a flag that enables `scalapb.UdtGenerator`, so it can be used in maven projects.

Thanks.

**Comment by jeffquinn-nuna** [comment]
Hey @thesamet,

Would love to help author a PR to add this functionality, since I need it for a project, but I am not 100% sure where to start. 

Would it be as simple as adding another item to "namedGenerators" here: https://github.com/scalapb/ScalaPB/blob/0a89478cfcc396cd247ad71edc715ac16de717ad/scalapbc/src/main/scala/com/trueaccord/scalapb/ScalaPBC.scala#L46

Containing the UDTGenerator. We could make it conditional on some kind of command line flag?

This may require making this project depend on https://github.com/scalapb/sparksql-scalapb/tree/master/sparksql-scalapb-gen which maybe you are trying to avoid, in which case we could just add another class to that project similar to ScalaPBC, and then that could be invoked separately in maven.

LMK what you think!

-Jeff

**Comment by thesamet** [comment]
ScalaPBC now supports a new command line flag formatted like this: `--custom-gen=${name}=${obj}` which would define a generator named `name` that is implemented by a Scala object named `obj` that must extend `ProtocCodeGenerator`.

For UDT generator, it would look like this: `--custom-gen=udt=scalapb.UdtGenerator --udt_out=path/to/generate`

For this to work, sparksql-scalapb-gen must be added as a plugin dependency to `exec-maven-plugin`.

A full example is available here: https://github.com/thesamet/scalapb-maven-example/blob/master/pom-udt.xml

One caveat, is that you need to upgrade to ScalaPB 0.7.x, which depending on how you use ScalaPB may require a few source code updates when upgrading.

**Comment by qwwqwwq** [comment]
Thanks! We will try that out.

**Comment by thesamet** [comment]
I put some migration information on ScalaPB 0.7.x here: https://groups.google.com/forum/#!topic/scalapb/BhM2IzT70Ww

**Comment by jeffquinn-nuna** [comment]
Thanks, everything works great aside from one small bug we found (probably pretty specific to our protos but could affect other people): https://github.com/scalapb/ScalaPB/issues/374
