### ISSUE TITLE
(scalapb.message).extends does not allow abstract classes

### ISSUE THREAD

**Issue by mushtaq** [scalapb/ScalaPB#342]
This is also the case with (scalapb.message).companion_extends and maybe other options. They admit only traits because it is mixed in last. It will be cool to support abstract classes (and putting them in front of others in the extension chain). This will allow automatically to pass typeclass instances like ClassTag and other application specific ones.

**Comment by thesamet** [comment]
If we move the user supplied class or trait to be first - any thoughts on how that might break users' existing code?

**Comment by mushtaq** [comment]
The linearlized chain of inheritance will be altered so it will break some
code. Maybe easier to introduce a separate option to mix classes/traits in
the first place.

**Comment by thesamet** [comment]
The main issue I have with it is that it will prevent ScalaPB from the possibility of introducing its own abstract base class in the future. Since the option to mix in traits makes it possible to achieve the same effect as mixing in an ABC (correct me if I'm wrong), then I prefer to leave it as it is.
