### ISSUE TITLE
`map<int64, google.protobuf.DoubleValue>` requires passing a not nullable `Map[Long, Double]`

### ISSUE THREAD

**Issue by mmatloka** [scalapb/ScalaPB#351]
Hi,
Proto3 ` primitive_wrappers: true`
When I define 
```
message Message {
    map<int64, google.protobuf.DoubleValue> data = 1;
}
```
I would expect a 
```
class Message(data: Map[Long, Option[Double]])
```
but `Map[Long, Double]` is generated. Underneath I can see some class for map entry is generated correctly with `Option[Double]` value but unfortunatelly it is transformed to mentioned not nullable Map.

**Comment by thesamet** [comment]
Hi @mmatloka, I agree this seems unexpected, though this behavior is consistent with how the generator works (in other words, there is no special case for primitive wrapper)

in ScalaPB primitive wrappers are type-mapped directly to the underlying type (`Double`, in this case, rather than to `Option[Double]`.  Whenever you have a `map<X,Y>` in a proto , you'll get a `Map[X,Y]` in Scala. So you are getting a `Map[Long, DoubleValue]` that becomes `Map[Long, Double]` after type-mapping.

The reason that primitive wrappers are wrapped in an option when they are a field in a message is that the original type would have been `Option[DoubleValue]`.

This behavior is also consistent with the official Java implementation which would generate:

```
    java.util.Map<java.lang.Long, com.google.protobuf.DoubleValue>
    getDataMap();
```
i.e., you won't have the ability to assign a key to the map with an empty values (nulls are not allowed))

Finally, to achieve the type signature you are trying to get, you'll need to wrap the `DoubleValue` in another message, and have that type-mapped to `Option[Double]`.
