### ISSUE TITLE
single_file option also when running standalone using spbc

### ISSUE THREAD

**Issue by lony** [scalapb/ScalaPB#414]
Could you provide the `single_file: true` as described [here](https://scalapb.github.io/customizations.html), even if the compiler is run via command line?

**Comment by thesamet** [comment]
Adding external parameters that significantly affect code generation turns out to cause usability issues due to interaction with other features. For example, the `preamble` option, requires single_file to be true. If we allow `single_file` to be an external parameter, then we can end up with a proto file that can be processed only when an external parameter is provided. If that file is later used as a dependency to another project that project is forced to use the external parameter as well. Having this setting at a file level avoids the issue.
