### ISSUE TITLE
0.7.0 of compilerplugin isn't published

### ISSUE THREAD

**Issue by acjay** [scalapb/ScalaPB#416]
The docs say to use version 0.7.0 of the compiler plugin, but that does not appear to have been published to Maven Central yet.

**Comment by acjay** [comment]
I was able to get this working with:

**project/scalapb.sbt**

```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.16")

libraryDependencies += "com.thesamet.scalapb" %% "compilerplugin" % "0.7.0"
```

**build.sbt**

```
lazy val protobuf = (project in file("protobuf"))
  .settings(
    scalaVersion := "2.12.3",
    PB.targets in Compile := Seq(
      scalapb.gen() -> (sourceManaged in Compile).value
    ),
    libraryDependencies += "com.thesamet.scalapb" %% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion % "protobuf"
  )
```

It complains with:

```
build.sbt:118: warning: value Version in package compiler is deprecated: Please use scalapb.compiler.Version
    libraryDependencies += "com.thesamet.scalapb" %% "scalapb-runtime" % com.trueaccord.scalapb.compiler.Version.scalapbVersion % "protobuf"
```

But still works.

**Comment by thesamet** [comment]
When it failed, is it possible you were using the previous maven coordinates (`com.trueaccord` instead of `com.thesamet.scalapb`)? We changed to `com.thesamet.scalapb` on 0.7.0. There are some notes on how to migrate here: https://scalapb.github.io/migrating.html

The warning you gave contains an explanation on how to fix it. Hope this helps. I think this resolves the issue, but let me know if I missed anything.
