### ISSUE TITLE
Empty messages should create a `case object` when used as part of oneof sealed traits

### ISSUE THREAD

**Issue by pjrt** [scalapb/ScalaPB#485]
Currently, the following will create an case class with no members. 

```proto
message Sealed {
  oneof sealed_value {
    EmptyMsg x = 1;
  }
}

message EmptyMsg {}
```

This will create a `final case class EmptyMsg() ...`. Why not just a `case object`?

**Comment by thesamet** [comment]
Generally, messages may have unknown fields which we need to keep track of, but we don't do it yet (see #406), so case objects wouldn't work there. For messages that participate in sealed one-ofs losing unknown fields is less of a concern. @olafurpg  - thoughts?

**Comment by olafurpg** [comment]
I agree it would be nice if there was a way to generate `case object` for empty messages. We have several empty messages in SemanticDB https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb3/semanticdb3.md#access

From a protobuf perspective, I think the current behavior makes sense since `message EmptyMsg {}` is a regular message that can gain fields in the future (or could have lost fields in the past). Would it be possible to introduce a ScalaPB message option to generate `case object` instead of `case class`? Would that be an acceptable solution @pjrt ?

**Comment by olafurpg** [comment]
OTOH, given that empty message appear so frequently in ADTs it maybe acceptable to generate case objects for empty messages by default 🤔 It would certainly improve our lives in Scalameta. From a protobuf perspective, sealed oneofs already have several unusual requirements. Good defaults are important, even if there was a message option to generate `case object` we would probably not use it in Scalameta since we have so far gotten away with custom options.

I likely won't work on this myself however.

**Comment by pjrt** [comment]
It is more of a sanity check (as well as PTSD. Back in the days, you used to get compiler errors on case classes with no actual params). 

I guess it isn't a big deal, but it is odd.
