### ISSUE TITLE
Feature Request: underscore naming compilation

### ISSUE THREAD

**Issue by adtm** [scalapb/ScalaPB#556]
I have seen that in the official Protobuf documentation (Google related), there is an opportunity to compile down to snake-case and not camel-case all the time.

```proto
message Foo {
  int32 value = 1 [json_name = "some_other_name"];
}
```

I think this would be viable, cause not all external service API's are camel-case and doing explicit mapping is not fun. 

(Maybe there is a solution how to do it - I just couldn't find it)

**Comment by thesamet** [comment]
Hi @adtm , AFAIK official protobuf does not provide this option. json_name can be set individually, but only affect JSON name, not the generated field name. ScalaPB provides an option called `scala_name` to alert a specific field. Since this works for the official protobufs and I would like to avoid unnecessary complexity. I can be convinced otherwise if there's increasing demand, or some opportunity that this enables.
