### ISSUE TITLE
Option compatibility with C# code generation

### ISSUE THREAD

**Issue by IndicatorFluid** [scalapb/ScalaPB#573]
I have a proto contract which uses scalapb options to flatten the package (due to the sad gradle plugin for scalapb not supporting that as a compiler option).

Including scalapb options in the contract requires me to put scalapb.proto on the include path, which is ok.

Other than the scala code, I am also generating C# code from the contract, which generates something like this:
```
new pbr::FileDescriptor[] { global::Foo.Contract.MyOwnOptionsReflection.Descriptor, global::Scalapb.ScalapbReflection.Descriptor, },
```

Now clearly there is no scalapb package for C#, so this won't work.
I can include scalapb.proto on the compilation path, but sadly because scalapb.proto is proto2 I get: 
```
--csharp_out: google/protobuf/compiler/plugin.proto: C# code generation only supports proto3 syntax
```

Which means I cannot use scalapb options and generate C# code at the same time.

I am not sure what the solution is in this case.

**Comment by thesamet** [comment]
It's worth considering for us to offer a scalapb.proto with syntax3. In the mean time, you can try making your own copy of scalapb.proto which uses proto3 syntax and contains the smallest subset that you actually need. Can you try that and update here?

**Comment by thesamet** [comment]
Looks like this issue is a combination of two limitations in other projects: C# generator not supporting proto2, and the Gradle not supporting passing generator parameter.

If you can switch to the official protobuf gradle plugin, ScalaPB now provides an artifact that can be used directly with it and you can use it pass options to the generator. See https://scalapb.github.io/faq.html#how-do-i-use-scalapb-with-gradle

There's nothing much I can do about the C# support for proto2, but I see little reason to provide a proto3 version right now. Might reconsider that in the future. As suggested before, you can set up your own mock `scalapb.proto` written in proto3 and set things up such that the build for C# picks up the mock version, but the build for Scala uses the real one.
