### ISSUE TITLE
CustomTypes not working for required fields

### ISSUE THREAD

**Issue by OlafurD** [scalapb/ScalaPB#576]
There seems to be a bug with the customTypeMapper for required fields. I've created a custom mapper for `java.util.UUID`, defined as such:

```
implicit val typeMapper: TypeMapper[String, UUID] =
      TypeMapper[String, UUID](str => {
        if(str == "") {
          println("EMPTY")
        }
        UUID.fromString(str)
      })(_.toString)
```

and my proto message definition:
```
message IdRequest {
    required string id = 1 [(scalapb.field).type = "java.util.UUID"];
}
```

when I run protoTool, passing in any arbitrary string for id will result in `EMPTY` being printed out. If I change the message definition to `optional` instead of `required`, the id parameter is successfully passed into the typeMapper

I'm using version 0.8.2 of the `scalapb-runtime`

**Comment by OlafurD** [comment]
Sure. Given this proto definition:

```
package com.foo;

message IdRequest {
    required string id = 1 [(scalapb.field).type = "java.util.UUID"];
}

message IdResponse {
    required string id = 1 [(scalapb.field).type = "java.util.UUID"];   
}

service FooService {
    rpc Foo (auctioncms.proto.IdRequest) returns (auctioncms.proto.IdResponse) {}
}
```

with this service implementation:
``` scala
class FooServiceImpl extends FooService {
  override def foo(request: IdRequest): Future[IdResponse] =
    Future.successful(IdResponse(java.util.UUID.randomUUID()))
}
```

Running this service locally, and calling it with prototool:
` prototool grpc ./src/protobuf --address localhost:8080 --method com.foo.FooService/Foo -- data '{"id": "74f7c232-21a9-477b-8896-c92a158a200b" }' `

will result in an empty string being passed into the `typeMapper`. If I change the above proto definition to `optional` instead of `required` and run prototool with the same parameters, the id is successfully passed into the typeMapper and my serviceImplementation is called

**Comment by thesamet** [comment]
The problem is that message parsing calls `IdRequest.defaultInstance` which needs to return a valid instance of the object and its implementation is passing an empty string through the typemapper. You could change the typemapper to return `new UUID(0,0)` for empty strings or alternatively change the proto file to be:

```
message IdRequest {
    required string id = 1 [default="00000000-0000-0000-0000-000000000000", (scalapb.field).type = "java.util.UUID"];
}
```

This would pass the following valid UUID through the typemapper and not cause the exception you are seeing.

This does not when you use an `Option` since the default value is `None` and the typemapper does not need to get invoked.

Once you pick one of the above options, it would work correctly: the value from the prototool command line would be passed to the UUID.

**Comment by OlafurD** [comment]
I see. Thanks a lot @thesamet !
