### ISSUE TITLE
sealed oneof without wrapper message per variant

### ISSUE THREAD

**Issue by dsilvasc** [scalapb/ScalaPB#577]
Would it be possible to support sealed oneofs without each variant needing to be a wrapper message?

For example, instead of

```proto
message Expr {
    oneof sealed_value {
        Literal lit = 1;
        ...
    }
}

message Literal {
    int32 value = 1;
}
```

would it be possible to support this as well?

```proto
message Expr {
    oneof sealed_value {
        int32 lit = 1;
        ...
    }
}
```

It would avoid the extra overhead on the wire representation from the wrapper message.

**Comment by thesamet** [comment]
When we generate Scala code we have all the oneof cases (in this example `case class Literal`) extend the base trait (`sealed trait Expr`). This can naturally be done when we generate messages, but for primitives (ints and longs) it isn't straightforward. One way around it would be to have ScalaPB generate wrappers for primtiives, and that's what ScalaPB already does for normal oneofs (non-sealed) - so that's already possible.

Hope this helps. Let me know if this gives a good explanation of the issue. Happy to discuss further if there are additional ideas.

**Comment by dsilvasc** [comment]
Thanks for the quick response.  That seems reasonable.  One suggestion: maybe consider inner messages as the variant types for each case, and synthesize them as you described otherwise.

For example:

```proto
message Expr {
    message Literal { int32 int_value = 1; }
    oneof sealed_value {
        Literal lit = 1;
        string primitive_example = 2;
        Other other_example = 3;
        Other yet_another_example = 3;
        ...
    }
}
```

might generate:

```scala
sealed trait Expr
object Expr {
  // from the inner message Expr.Literal
  case class Literal(intValue: Int) extends Expr
  // generated wrapper for primitive
  case class PrimitiveExample(value: String) extends Expr
  // generated wrapper for message type that isn't an inner message of Expr
  case class OtherExample(value: Other) extends Expr
  // also generated even though it also contains an Other like the other_example field
  case class YetAnotherExample(value: Other) extends Expr
}
```

**Comment by thesamet** [comment]
Yes, it can be done, but I am not sure if the complexity of inconsistent treatment of message and non-message types is worth the hassle. Happy to reconsider this if there's demand.

Also, from my anecdotal experience with protobuf applications, I would encourage schema authors to avoid primitive fields inside oneofs due to schema evolution considerations: if you have a message - it's possible to add additional fields to that case, but when you have a primitive, the only way to extend is to add a new case.
