### ISSUE TITLE
standalone protoc plugin on maven

### ISSUE THREAD

**Issue by ckchow** [scalapb/ScalaPB#579]
Now that scalapb generates a standalone protoc plugin, it would be really cool if the project also published standalone `protoc-gen-scala` artifacts to maven in a form that the widely-used gradle-protobuf-plugin could use. `grpc` seems to accomplish this by publishing a pom and a bunch of exes: https://github.com/grpc/grpc-java/blob/master/compiler/build.gradle#L284

**Comment by thesamet** [comment]
It looks like gradle would be looking for things that are organized like this: http://central.maven.org/maven2/io/grpc/protoc-gen-grpc-java/1.20.0/

Since our plugin is JVM based, we can make our executables using sbt-assembly by [prepending a launch script](https://github.com/sbt/sbt-assembly#prepending-a-launch-script).

On Windows, the filename would have to end with a `.bat` extension. Is there any documentation on the layout gradle is expecting? Is it possible to make Gradle get a BAT file instead of a binary executable?

**Comment by thesamet** [comment]
Done. See https://scalapb.github.io/faq.html#how-do-i-use-scalapb-with-gradle
