### ISSUE TITLE
Feature Request: `BitSet` as `collection_type`

### ISSUE THREAD

**Issue by bjchambers** [scalapb/ScalaPB#628]
I would like to use a `BitSet` as a collection corresponding to a `Seq[Int]`
```
  repeated int32 bitset = 1 [(scalapb.field).collection_type = "scala.collection.immutable.BitSet"];
```

This seems like it should be do-able, but as written it won't compile, since it attempts to use `BitSet[Int]` as the type, and `BitSet` doesn't take parameters.

Could this be made to work? One thought would be if the specified `collection_type` doesn't take generics, or already extends `Seq[Int]` then it can be used directly, rather than passing in a generic? Not sure how hard this would be to add...

**Comment by bjchambers** [comment]
Both the existing `type` and `scala_name` apply to the elements, not the collection itself, so there does not seem to be a way (currently) to remap the collection type in this way.

**Comment by plokhotnyuk** [comment]
BitSet allocates memory depending on added values. So for security reasons it is need to have some configurable limit of max values allowed for them to prevent OOM errors in case of malicious input.

**Comment by thesamet** [comment]
@bjchambers here are two ways you can accomplish it

# Option 1: create a type alias

In one of your Scala files
```
package myexample

object hacks {
  type BitSet[_] = collection.immutable.BitSet

  object BitSet {
    def newBuilder[T] = collection.immutable.BitSet.newBuilder

    def empty = collection.immutable.BitSet.empty
  }
} 
```

In your proto file:
```
  repeated int32 bitset = 1 [(scalapb.field).collection_type = "myexample.hacks.BitSet"];
```

Now `example.hacks.BitSet` takes one type parameter, so it is compatible is what ScalaPB expects. Since our hack is just a type alias, you can pass in normal bitsets.

# Option 2: create a wrapper type

In a proto file (we will assume it is named bitset.proto):

```
syntax = "proto3";  // proto2 works too

import "scalapb/scalapb.proto";

package myexample;

message BitsetWrapper {
  option (scalapb.message).type = "collection.immutable.BitSet";
  repeated int32 values = 1;
}
```

In a scala file we create an implicit typemapper that can convert back and from BitsetWrapper:

```
import scalapb.TypeMapper
import collection.immutable.BitSet
import myexample.proto2.BitsetWrapper

package object myexample {
  implicit val tm: TypeMapper[BitsetWrapper, BitSet] =
    TypeMapper { w: BitsetWrapper => BitSet(w.values: _*) } { t: BitSet => BitsetWrapper(t.toVector) }
}
```

Use it like this:
```
message Person2 {
  optional string name = 1;
  optional int32 age = 2;
  optional BitsetWrapper my_bitset = 3 [(scalapb.field).no_box = true];
}
```

The `no_box` is necessary so it doesn't generate `Option[BitSet]`.

The tradeoffs: the second solution introduces a wrapper and there is going to be a conversion between vectors and bitsets at runtime that can impact performance if you have large bitsets. The first solution builds BitSets directly without conversion through a vector, but there is some possibility that the type alias will leak into your code.

I woulld recommend trying the first solution for a while, and we can see if further work on it is needed.

**Comment by bjchambers** [comment]
Thanks!
