### ISSUE TITLE
Case insensitive enum parsing

### ISSUE THREAD

**Issue by ashamukov** [scalapb/ScalaPB#632]
Hello! What do you think about a flag inside scalapb.json4s.Parser.ParserConfig, that will tell `defaultEnumParser` that enum values' names should be compared ignore case?
In this line:
```
enumDescriptor.values.find(_.name == s).getOrElse(throw new JsonFormatException(s"Unrecognized
```

Looks like pretty wide-used scenario. I could come up with a PR.
Thank you!

**Comment by thesamet** [comment]
Hey @ashamukov,  I'd prefer to have scalapb-json4s produce and consume JSON that conform to the spec: https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by ashamukov** [comment]
Hello Nadav! Thanks for the answer! Yes, it looks like the spec implies exact equality of enum names, and the flag would look like not-very-native customization. 

So, lets go to more general solution, which would be to support 'json_name' option for enum values: https://github.com/protocolbuffers/protobuf/issues/4328

**Comment by thesamet** [comment]
The proposal to add `json_name` to `EnumValueDescriptors` is reasonable, but there is no clarity on whether or when that is going to happen. Rather than keeping this issue as blocked for indetermined amount of time, I will close for now. Let's reopen or file a new issue once there is a forward path.
