### ISSUE TITLE
ByteString serialversionUid different in 0.8.2 vs 0.9.0 (seeing issue in deserialization)

### ISSUE THREAD

**Issue by rajeshkalaria80** [scalapb/ScalaPB#635]
We were using "com.thesamet.scalapb" %% "compilerplugin" % "**0.8.2**" to generate protobuf classes. With that version, when we used to generate our application jar and when I inspected serial version uid of ByteString class, it was **-210482779550467059L**, and with this version, we have some data persisted/serialized in database.

Then recently, we moved to "com.thesamet.scalapb" %% "compilerplugin" % "**0.9.0**", with that the serial version uid of ByteString class is **2917209575369780126L**, but during deserialization of previously persisted/serialized data, it gives error something like this:

com.google.protobuf.ByteString; local class incompatible: stream classdesc serialVersionUID = -210482779550467059, local class serialVersionUID = 2917209575369780126

Was that intended?
Do we have any migration path for it or any help I can get here on this?

**Comment by thesamet** [comment]
Hi @rajeshkalaria80 , `com.google.protobuf.ByteString` is provided by `protobuf-java`, not by ScalaPB, however looking at the [source code](https://github.com/protocolbuffers/protobuf/blob/c60aaf79e63b911b2c04c04e1eacb4f3c36ef790/java/core/src/main/java/com/google/protobuf/ByteString.java#L1285), they have not changed the `serialVersionUID` recently, it seems to be `1`.

Since you mention serialVersionUID, I infer that you have not been serializing and deserializing in protobuf standard format (using methods like `toByteArray` and `parseFrom`), but instead used Java serialization directly (can you confirm?). Serialization in protobuf format gives you a binary representation that does not depend on the version of ScalaPB you are using, and specifically not on `serialVersionUID`. It looks like the way you serialized does depend on the specific version and implementation of ScalaPB/protobuf-java which can change between versions.

Suggested migration path: revert back to ScalaPB 0.8.2, deserialize your data in the old way, and re-serialize it in protobuf format (`toByteArray`). You can add a new column in your database that indicates the format of each row (for example,`0` means your old format, `1` means proto format), and you make sure the code that reads from the database knows how to deal with the two formats.

**Comment by rajeshkalaria80** [comment]
@thesamet , thanks for your quick reply. We are using protobuf standards (using methods like toByteArray and parseFrom) to serialize and deserialize.

Yes, in my recent finding also it is confirmed that it is not directly ScalaPB issue. But serial version uid is for sure changed by protobuf-java, here is the confirmation:

serialver -classpath protobuf-java-3.6.1.jar com.google.protobuf.ByteString
	private static final long serialVersionUID = -210482779550467059L;

serialver -classpath protobuf-java-3.7.1.jar com.google.protobuf.ByteString
	private static final long serialVersionUID = 2917209575369780126L;

But, I tried to reproduce this issue locally for one of the akka actor (meaning I used compilerplugin 0.8.2, persisted some data, then I used compilerplugin 0.9.0), and I couldn't reproduce it. So, seems, it is not as bad as I thought, it is only happening for one of our actor, so let me dig into it more and there might be a chance that we might be doing something different for that specific actor and thats why we see this issue.

I'll close this issue, thanks again for your quick help.
