### ISSUE TITLE
Message case classes inside of common object

### ISSUE THREAD

**Issue by otto-dev** [scalapb/ScalaPB#751]
I have a question (no blocker) in regard to using Protobuf with [Akka](https://akka.io/). Especially in Akka Typed you typically have the protocol case classes inside the companion object of the Actor.

```scala
object SomeActor {
  sealed trait Command
  case class CommandOne(foo: String) extends Command
  case class CommandTwo(bar: String) extends Command
  
  def apply: Behavior[Command] = ??? // create the actor/behavior
}
```

This allows to prefix messages to other actors with their object name for clarity:

```scala
  // other actor
  def apply(): Behavior[Command] = Behaviors.receive { (context, message) =>
    val actor: Behavior[SomeActor.Command] = context.spawn(SomeActor(), "partner")
    actor ! SomeActor.CommandOne("foo") // SomeActor prefix
  }
```

An alternative would be to have a separate object for the message classes, such as `SomeActorProtocol`, so that you can reference the messages as `SomeActorProtocol.Command`

A question how to do this for Protobuf messages previously came up [here](https://discuss.lightbend.com/t/akka-typed-and-protobuf-serialization/560)

Is there currently any way to have message classes inside of an `object`, ideally a companion object (eg. of an actor)? Would having `postamble` make it possible, by opening an object in `preamble` and closing the object in `postable`?

**Comment by thesamet** [comment]
The easiest thing to do would just to wrap the messages in your proto files within some other message:

```proto
message Container {
  Message A {}
  Message B {}
}
```

The case classes for `A` and `B` will be generated inside an object named `Container`. There's also going to be a case class named `Container` that you can ignore. Using `preamble` and a potential `postamble` wouldn't do, since ScalaPB needs to know the Scala name of the classes it generates so other generated code can refer correctly to them. In other words, this can lead to compilation errors if you have messages in other protos referencing to these wrapped messages.

Theoretically, we could add a file-level option for having all classes in a proto go under an object of a given name - but I think that the wrapper approach described above should be sufficient.

**Comment by otto-dev** [comment]
>  I think that the wrapper approach described above should be sufficient.

Agreed! Great that this works, I'll test it later.

I'll mention this in the thread linked earlier.
