### ISSUE TITLE
Type safe equals method for enums

### ISSUE THREAD

**Issue by mattdornfeld** [scalapb/ScalaPB#815]
Is it possible to have a type safe equals method for generated enums? For example. if I try to compare two enums of different types can I get an error at compile time?

**Comment by thesamet** [comment]
In case one enum is stored in a val and the other one is a constant (a very common case), it is recommended to use the `isX` methods which return a boolean: `color.isBlue`, `color.isRed`, and os on, rather than compare.

What type of solution are you looking for? A new method, say `===` that's defined on the enum type and would only accept an argument of the same type? That should be pretty straightforward to do in your own project through implicit conversion.

**Comment by mattdornfeld** [comment]
That's perfect. Thank you.
