### ISSUE TITLE
`ProtoParquetReader` does not iterate over the parquet file correctly with ScalaPB generated classes

### ISSUE THREAD

**Issue by paualarco** [scalapb/ScalaPB#844]
Using the ScalaPB generated classes I am getting issues on reading back a parquet as protobuf events. 

I doubt this error is because of the java proto generated message that this library supports, it is more likely to be a problem on the `parquet-protobuf`. 

Although you might have had similar issues before with that... and that's why I am raising the issue here. See there is also an [issue](https://issues.apache.org/jira/browse/PARQUET-1871) raised to the apache parquet project.

Actual issue is:

The `ProtoParquetReader` does not iterate over the parquet file correctly, but it gets stuck in the first element and keeps reading as many times as elements the file contained.

In my Scala example I am just reading from a local file that I know for sure it contains right data.

```
val hadoopCOnf = new Configuration()

val outfile: String = genTemporaryFile()

val r: ParquetReader[Event.Builder] =

{ ProtoParquetReader.builder[Event.Builder](new Path(outfile)).withConf(hadoopCOnf).build() }
```

See an example on how the ProtoParquetReader is created line(65 and 69): https://github.com/monix/monix-connect/blob/master/parquet/src/test/scala/monix/connect/parquet/ProtoParquetFixture.scala#L69

and here how it is used (notice that is defined for only one record, the same one for multiple records would fail) https://github.com/monix/monix-connect/blob/master/parquet/src/test/scala/monix/connect/parquet/ProtoParquetSpec.scala#L83

**Comment by thesamet** [comment]
Hi @paualarco , as far as I know, ProtoParquetReader is designed to work with Google's official Java generated code for protobufs, not with ScalaPB's. To make this work, I believe we would have to write a different `ProtoParquetReader` that works with ScalaPB.

If you'd like we can collaborate on building such a new project in ScalaPB, if you are able to work on it.

**Comment by paualarco** [comment]
And how is it that there are no issues when using `ProtoParquetWriter` with `ScalaPB` generated protos?
Would that project be an addition to `ScalaPB` or `apache parquet`? If that's posible I would like to help building it, but not have much idea where to start from.

**Comment by thesamet** [comment]
@paualarco I am a bit surprised that it works at all - the API is completely different. The [code here](https://github.com/apache/parquet-mr/blob/dc61e510126aaa1a95a46fe39bf1529f394147e9/parquet-protobuf/src/main/java/org/apache/parquet/proto/ProtoWriteSupport.java) seems to be specific for Google's Java protobuf. 

It would be easier to add a project to the ScalaPB org (I am not affiliated with apache parquet).

In the past, we had something similar to this project in sparksql-scalapb which was IIRC correctly mixed with Spark. I assume that you want to read parquets outside Spark (since inside Spark things just work). You can start working off the deleted code here: https://github.com/scalapb/sparksql-scalapb/commit/7385f10774f41af5b723282655f3e268e051b012 and compare it to the apache project.

**Comment by thesamet** [comment]
I believe there's nothing actionable for ScalaPB. Please feel free to raise another issue if there's anything that needs to be done.
