### ISSUE TITLE
Upgrade scalapb.proto syntax to proto3?

### ISSUE THREAD

**Issue by RyanBerti** [scalapb/ScalaPB#936]
Hello,

We use the uber1 prototool lint rule internally, and there are many lint rules that the scalapb.proto definition doesn't follow, requiring us to explicitly ignore many rules for this specific proto file. I have to include the scalapb.proto file in my schema repo which `prototool lint` is run against because I need to specify some extra scalapb configuration options in an internal proto file I am working with. Is there any plan to upgrade syntax of the scalapb.proto file, or has anyone else raised this type of issue?

Ryan

**Comment by thesamet** [comment]
Hi @RyanBerti , there's currently no concrete plan on providing a proto3 version of scalapb.proto, because the logic of merging options between different files relies on presence of primitive values. There's experimental support for optional fields in proto3, but it would be too early at this point to expect proto3 users to enable the experimental protoc flag.

There are a few options:
1. Can you exclude scalapb.proto from your linter? Generally you don't want to lint third-party code that you don't control - it's unlikely to comply with your company's style guides.
2. If there are minor changes to scalapb.proto to make it compliant with the uber tool, I am willing to take a PR (moving to proto3 wouldn't be minor, so if that's a requirement of the lint tool it's a good reason to go with option 1)
3. build your own scalapb.proto in proto3 and compile using the experimental presence flag and make it acceptable to the lint tool. This would work since the binary representation of your scalapb.proto would be the same as the proto2 binary representation.

More on the experimental protoc feature: https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

**Comment by RyanBerti** [comment]
@thesamet thanks for the quick response - I was able to exclude the scalapb.proto file from the linter and move forward. Thanks for all your work on these scala-focused projects!
